export const Productos = [
  {
    id: 1,
    name: "tomate",
    img: "images/tomate.svg",
    price: 1.4,
    measurement: "Kilo",
  },
  {
    id: 2,
    name: "Zanahoria",
    img: "images/zanahoria.svg",
    price: 0.60,
    measurement: "Kilo",
  },
  {
    id: 3,
    name: "cebollas",
    img: "images/cebollas.svg",
    price: 0.90,
    measurement: "Kilo",
  },
  {
    id: 4,
    name: "maiz",
    img: "images/maiz.svg",
    price: 1.5,
    measurement: "ud.",
  },
  {
    id: 5,
    name: "champiñon",
    img: "images/champiñon.svg",
    price: 0.95,
    measurement: "Kilo",
  },
  {
    id: 6,
    name: "pepino",
    img: "images/pepino.svg",
    price: 0.90,
    measurement: "Kilo",
  },
  {
    id: 7,
    name: "calabacin",
    img: "images/calabacin.svg",
    price: 0.80,
    measurement: "Kilo",
  },
  {
    id: 8,
    name: "pimiento rojo",
    img: "../images/pimiento_rojo.svg",
    price: 1.30,
    measurement: "Kilo",
  },
  {
    id: 9,
    name: "esparragos",
    img: "../images/esparragos.svg",
    price: 2.80,
    measurement: "ud.",
  },
  {
    id: 10,
    name: "alcachofa",
    img: "images/alcachofa.svg",
    price: 2.50,
    measurement: "Kilo",
  },
  {
    id: 13,
    name: "berenjena",
    img: "images/berenjena.svg",
    price: 1.20,
    measurement: "Kilo",
  },
  {
    id: 14,
    name: "puerros",
    img: "images/puerros.svg",
    price: 2,
    measurement: "Kilo",
  },
  {
    id: 11,
    name: "col",
    img: "images/col.svg",
    price: 1.60,
    measurement: "Kilo",
  },
  {
    id: 12,
    name: "brocoli",
    img: "images/brocoli.svg",
    price: 2,
    measurement: "Kilo",
  },
  {
    id: 13,
    name: "coliflor",
    img: "images/coliflor.svg",
    price: 1.10,
    measurement: "Kilo",
  },
  {
    id: 14,
    name: "uvas",
    img: "../images/uvas.svg",
    price: 2.60,
    measurement: "Kilo",
  },
  {
    id: 15,
    name: "naranja",
    img: "../images/naranja.svg",
    price: 1.40,
    measurement: "Kilo",
  },
  {
    id: 16,
    name: "limón",
    img: "images/limon.svg",
    price: 1.90,
    measurement: "Kilo",
  },
  {
    id: 17,
    name: "brocoli",
    img: "images/brocoli.svg",
    price: 1.80,
    measurement: "ud.",
  },
  {
    id: 18,
    name: "piña",
    img: "images/piña.svg",
    price: 1.30,
    measurement: "Kilo",
  },
  {
    id: 19,
    name: "ciruela",
    img: "images/ciruela.svg",
    price: 2.30,
    measurement: "Kilo",
  },
  {
    id: 20,
    name: "manzana",
    img: "../images/manzana.svg",
    price: 1.80,
    measurement: "Kilo",
  },
  {
    id: 21,
    name: "platano",
    img: "images/platanos.svg",
    price: 1.10,
    measurement: "Kilo",
  },
  {
    id: 22,
    name: "lata_guisantes",
    img: "images/lata_guisantes.svg",
    price: 0.80,
    measurement: "ud.",
  },
  {
    id: 23,
    name: "lata_maiz",
    img: "images/lata_maiz.svg",
    price: 1.05,
    measurement: "ud.",
  },
   {
    id: 24,
    name: "pan barra",
    img: "images/pan_barra.svg",
    measurement: "ud.",
  },
  {
    id: 25,
    name: "pan rústico",
    img: "images/pan_rustica.svg",
    price: 1.80,
    measurement: "ud.",
  },
  {
    id: 26,
    name: "pan trenza",
    img: "images/pan_trenza.svg",
    price: 1.10,
    measurement: "ud.",
  },
  {
    id: 27,
    name: "madalena",
    img: "images/madalena.svg",
    price: 1.80,
    measurement: "ud.",
  },
  {
    id: 28,
    name: "agua",
    img: "images/agua.svg",
    price: 0.45,
    measurement: "ud.",
  },
  {
    id: 29,
    name: "zumo naranja",
    img: "../images/zumo_naranja.svg",
    price: 1.30,
    measurement: "Kilo",
  },
  {
    id: 30,
    name: "leche",
    img: "images/leche.svg",
    price: 0.80,
    measurement: "ud.",
  },
  {
    id: 31,
    name: "patatas clásicas",
    img: "images/chips_clasicas.svg",
    price: 1.05,
    measurement: "ud.",
  },
  {
    id: 32,
    name: "patatas queso",
    img: "images/chips_queso.svg",

    price: 1.20,
    measurement: "ud.",
  },
];

